### ISSUE TITLE
Library projects should have a public_name field

### ISSUE THREAD

**Issue by shonfeder** [CraigFe/oskel#13]
iiuc, `oskel --kind library` should generate a project fit for use as a package, which can be imported by another project. afaik, this requires that the generated `dune` file for the principle library provided have a `public_name` field.

**Comment by CraigFe** [comment]
Yep, you're right. I misunderstood the `public_name` field when I wrote this.

(The `public_name` field is also necessary for Odoc to generate any documentation, AFAIU.)

**Comment by CraigFe** [comment]
Should be fixed now. Thanks for the report.
