### ISSUE TITLE
Bug: Can't install on macos 10.14.6

### ISSUE THREAD

**Issue by raguay** [CraigFe/oskel#2]
I can't install on my macos 10.14.6. I get this error:

 $ opam pin add --yes https://github.com/CraigFe/oskel                             Tue Jan 07 15:25 00:00:01 
Processing: [oskel: http]
[oskel] downloaded from https://github.com/CraigFe/oskel
[ERROR] Could not retrieve Unknown archive type:
        /private/var/folders/wg/zz5h9br17xl76_k2755c5wtr0000gn/T/opam-86976-9b8556/oskel

I've been trying to get an ocaml setup to learn the language, but I'm having a hard time getting things to work.

**Comment by CraigFe** [comment]
Thanks for the issue. This was a typo I made when creating the installation instructions: you need a `.git` prefix for Git HTTPS remotes, so something like:
```
opam pin add --yes https://github.com/CraigFe/oskel.git
```
should work for you. I've fixed this in https://github.com/CraigFe/oskel/pull/3.

**Comment by CraigFe** [comment]
Feel free to re-open if you still have issues installing :slightly_smiling_face:

**Comment by raguay** [comment]
It still will not install. I had to redo my ~/.opam directory in order to run these commands. But, as you can see, they are erroring:

 $ opam pin add --yes https://github.com/CraigFe/oskel.git                         Tue Jan 07 20:52 00:00:00 
Processing: [oskel: git]
[oskel] synchronised from git+https://github.com/CraigFe/oskel.git
Package oskel does not exist, create as a NEW package? [Y/n] y
[oskel.~dev] synchronised from git+https://github.com/CraigFe/oskel.git
oskel is now pinned to git+https://github.com/CraigFe/oskel.git (version ~dev)
The following dependencies couldn't be met:
  - oskel → unix
      unknown package

[NOTE] Pinning command successful, but your installed packages may be out of sync.

 $ opam install oskel                                                              Tue Jan 07 20:53 00:00:00 

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><>  🐫 
[oskel.~dev] no changes from git+https://github.com/CraigFe/oskel.git

The following dependencies couldn't be met:
  - oskel → unix
      unknown package

No solution found, exiting

**Comment by CraigFe** [comment]
That one was a silly mistake on my part, fixed by https://github.com/CraigFe/oskel/commit/58cf8a39cac78fc2c756449a0c3361d7a98a0c64. Currently in the process of adding CI to this repository...

**Comment by raguay** [comment]
It’s now dying with:

[ERROR] The compilation of oskel failed at "/Users/raguay/.opam/opam-init/hooks/sandbox.sh build dune build -p
        oskel -j 3 @install".

#=== ERROR while compiling oskel.~dev =========================================#
# context     2.0.5 | macos/x86_64 | ocaml-system.4.08.1 | pinned(git+https://github.com/CraigFe/oskel.git#58cf8a39)
# path        ~/.opam/default/.opam-switch/build/oskel.~dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p oskel -j 3 @install
# exit-code   1
# env-file    ~/.opam/log/oskel-76288-e18f3c.env
# output-file ~/.opam/log/oskel-76288-e18f3c.out
### output ###
# File "bin/dune", line 3, characters 55-63:
# 3 |  (libraries cmdliner fmt fmt.cli fmt.tty logs logs.cli logs.fmt oskel))
#                                                            ^^^^^^^^
# Error: Library "logs.fmt" not found.
# Hint: try: dune external-lib-deps --missing -p oskel -j 3 @install



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build oskel ~dev
└─ 
┌─ The following changes have been performed
│ ∗ install cmdliner     1.0.4
│ ∗ install conf-m4      1
│ ∗ install dune         2.0.1
│ ∗ install fmt          0.8.8
│ ∗ install ocamlbuild   0.14.0
│ ∗ install ocamlfind    1.8.1
│ ∗ install seq          base
│ ∗ install stdlib-shims 0.1.0
│ ∗ install topkg        1.0.1
└─

**Comment by CraigFe** [comment]
Apologies. More missing configuration in `dune-project`, now added. 

Unfortunately, Dune doesn't check that it's only relying on dependencies that you've told it about via `dune-project`.

**Comment by raguay** [comment]
Thanks. It's working now. Glad to help debug. Now, on to learning Ocaml.
